### ISSUE TITLE
Transfor ownership to libmir

### ISSUE THREAD

**Issue by ljubobratovicrelja** [ljubobratovicrelja/mir.experimental.model.rbf#2]
@9il, I'd like to transfer ownership of this repo to libmir org. Would that be ok? If so, would you like me to change repo's name to something more suitable?

**Comment by 9il** [comment]
yes
may be `mir-neural`?

**Comment by ljubobratovicrelja** [comment]
Done. Anything else you require of me to do regarding this change, just name it. ;)
